### --- loading the libraries --- ###

library(shiny)
library(shinyWidgets)
library(data.table)
library(tree)
library(rpart)
library(rpart.utils)
library(rpart.plot)
library(class)
library(randomForest)
library(randomForestExplainer)
library(dplyr)
library(markdown)
library(gbm)
library(caret)
library(rattle)


### --- creating datasets --- ###

drugs = read.csv("drug200.csv", header = TRUE, sep = ",")

### --- creating train and test split --- ###

set.seed(345)
train.index = createDataPartition(drugs$Drug, p = 0.7, list = FALSE)
train_data = drugs[train.index,]
test_data = drugs[-train.index,]


### --- Creating list for our features for decision tree and random forest --- ###

allfeatures = list("Age", "Sex", "BP", "Cholesterol", "Na_to_K", "Drug") # all features are being selected

### --- DECISION TREE (caret) --- ###
### --- Creating the train model for decision tree --- ###

makeTree = function(features = allfeatures, min_split, min_bucket, max_depth) {
  
  ### --- parameter (int) as inputs and then returns an rpart classification tree --- ###
  ### --- created with those parameters using Gini-indexes without any pruning --- ###
  ## --- create an rpart compatible formula for the model from the chosen vars --- ##
  ## --- rpart performs the split calculations and returns the tree --- ##
  
  tree = rpart(
    'Drug ~ . ',
    method = "class",
    data = train_data,
    parms = list(split = "gini"), # ensure rpart uses gini indexes
    minsplit = min_split,
    minbucket = min_bucket,
    maxdepth = max_depth,
    cp = 0 ## complexity parameters at zero prevents pruning on branches
  )
  
  return(tree)
}

### --- Creating test model for decision tree --- ###

useTree = function(tree, data) {
  
  ## --  takes a tree generated by rpart and a data (string) as input and
  # then predicts the labels of the data in that file using the tree --- ###
  
  prediction = predict(tree, data, type = "class")
  results = as.data.frame(prediction)
  results$truth = data$Drug
  
  return(results)
}

### --- RANDOM FOREST --- ###
### --- Creating the train random forest --- ###

rftrain = function(features = allfeatures, ntree){
  key_formula = paste("Drug~", paste(allfeatures, collapse = "+"))
  fitControl = trainControl(method = "repeatedcv", number = 5,
                            repeats = 3)
  set.seed(10)
  rforest = train(as.formula(key_formula), data = train_data, method = "rf", metric = "Accuracy",
                  trControl = fitControl, ntree = ntree, tuneLength = 4, localImp = TRUE)
  return(rforest)
  
}

### --- Creating test model for random forest --- ###

testforest = function(rforest, data){
  prediction = predict(rforest, data, type = "prob")
  results = as.data.frame(prediction)
  results$truth = data$Drug
  return(subset(results, select = c(truth, prediction)))
}


### --- Both forest and decision tree scores --- ###

calcScores = function(results) {
  ## -- takes a results dataframe as input and then calculates scores for
  # accuracy, true negative rate, and true positive rate. It returns a
  # list of formatted strings detailing these results -- ##
  
  results = table(results)
  
  # calculate the scores on which we'll judge our model to 2 decimal places
  
  accuracy = round(100 * (results[1] + results[4]) / sum(results), 2)
  
  # the collapse argument removes the spacing which would otherwise be there
  return(list(
    paste(c("Overall Accuracy: ",   accuracy, "%"), collapse = "")
  ))
}


ui <- fluidPage(navbarPage("Decision Tree and Random Forest for Drug Types: ",
                           tabPanel("Decision Tree",
                                    titlePanel(title = div("Drug Type")), 
                                    p("Finding the right treatment, whether you're looking for drugs to treat 
    seasonal allergies or you're treating a serious illness."),
                                    sidebarLayout(
                                      sidebarPanel(
                                        
                                        h1("The Controls"),
                                        br(),
                                        
                                        actionButton(
                                          inputId = "createModel",
                                          label = "Create Model",
                                          class = "btn-primary"
                                        ),
                                        helpText(
                                          "Pressing this blue button creates a decision tree model for",
                                          "the training data, based on the features selected and",
                                          "the chosen parameter values. Use this while you're",
                                          "developing your model; changing the selected features",
                                          "and pressing it again regenerates the new model."
                                        ),
                                        br(), br(),
                                        
                                        actionButton(
                                          inputId = "testModel",
                                          label = "Test Model",
                                          class = "btn-danger"
                                        ),
                                        helpText(
                                          "Press the above red",
                                          "button to run it on the test data. Use this when you are ready to assess your model."
                                        ),
                                        br(),
                                        
                                        strong("What is your gender?"),
                                        br(),
                                        
                                        switchInput("switchsex", value = TRUE , onLabel = "Male", offLabel = "Female"),
                                        br(),
                                        
                                        selectInput("Blood Pressure", label = p("What is your blood pressure?"),
                                                    choices = list("HIGH" = 2, "NORMAL" = 1, "LOW" = 0), selected = 0),
                                        br(),
                                        
                                        selectInput("Cholesterol", label = p("Cholesterol levels"),
                                                    choices = list("HIGH" = 1, "NORMAL" = 0), selected = 0),
                                        br(),
                                        
                                        noUiSliderInput(
                                          inputId = "form1",
                                          min = 0, max = 35,
                                          value = 15,
                                          format = wNumbFormat(decimals = 3, thousand = "", prefix = "Sodium to potessium ratio: ")),
                                        br(),
                                        
                                        knobInput(
                                          inputId = "myKnob",
                                          label = "Age",
                                          value = 25,
                                          min = 0,
                                          max = 80,
                                          displayPrevious = TRUE,
                                          lineCap = "round",
                                          fgColor = "#428BCA",
                                          inputColor = "#428BCA"
                                        ),
                                        br(),
                                        
                                        h4("Minimum Split"),
                                        helpText(
                                          "If at a given node N is below this value, that node cannot",
                                          "be split any further: it is a terminal node of the tree."
                                        ),
                                        sliderInput(
                                          inputId = "min_split",
                                          label = NULL,
                                          min = 2,
                                          max = 10,
                                          value = 2
                                        ),
                                        br(),
                                        
                                        h4("Minimum Bucket Size"),
                                        helpText(
                                          "If creating a given split would cause N₁ or N₂ to fall below",
                                          "this minimum, then that split isn't made part of the",
                                          "decision tree."
                                        ),
                                        sliderInput(
                                          inputId = "min_bucket",
                                          label = NULL,
                                          min = 1,
                                          max = 10,
                                          value = 1
                                        ),
                                        br(),
                                        
                                        h4("Maximum Tree Depth"),
                                        helpText(
                                          "Control the maximum depth that the decision tree can reach.",
                                          "Note that, depending on what features are being used and the",
                                          "values of the other parameters, you may end up with a tree",
                                          "much shallower than the maximum."
                                        ),
                                        sliderInput(
                                          inputId = "max_depth",
                                          label = NULL,
                                          min = 2,
                                          max = 5,
                                          value = 5
                                        ),
                                        br(),
                                        
                                      ),
                                      mainPanel(
                                        fluidRow(
                                          label = NULL,
                                          column(6,
                                                 h2("Training Results"),
                                                 helpText(
                                                   "These are the measures of how good your model was",
                                                   "when it was ran on the training data set."
                                                 ),
                                                 tagAppendAttributes(
                                                   textOutput("training_scores"),
                                                   style = "white-space: pre-wrap; font-size: 17px;"
                                                 ),
                                                 br(),
                                                 tableOutput("training_table")
                                          ),
                                          column(6,
                                                 h2("Test Results"),
                                                 helpText(
                                                   "These are the measures of how good your model was",
                                                   "when it was ran on the test data set. Interpret",
                                                   "the differences between these measures and the measures",
                                                   "from the training data."
                                                 ),
                                                 # test accuracy, true positive, and true negative
                                                 tagAppendAttributes(
                                                   textOutput("test_scores"),
                                                   # allow linebreaks between scores, larger font here
                                                   style = "white-space: pre-wrap; font-size: 17px;"
                                                 ),
                                                 br(),
                                                 # training results table matches layout from presentation
                                                 tableOutput("test_table")
                                          )  
                                        ),
                                        h2("Decision Tree"),
                                        helpText(
                                          "This is a graphical depiction of the decision tree."),
                                        plotOutput(outputId = "tree_plot"),
                                        br(),
                                      )
                                    ),
                           ),
                           tabPanel("Random Forest",
                                    titlePanel(title = div("Random Forest measures: ")), 
                                    sidebarLayout(
                                      sidebarPanel(
                                        
                                        actionButton(
                                          inputId = "createModel_rforest",
                                          label = "Create Model",
                                          class = "btn-primary"
                                        ),
                                        br(),
                                        
                                        h4("Number of mtry: "),
                                        helpText(
                                          "Number of variables randomly sampled as candidates at each split."
                                        ),
                                        sliderInput(inputId = "mtry",
                                                    label = NULL,
                                                    min = 1,
                                                    max = 6,
                                                    value = 2,
                                                    step = 1),
                                        br(),
                                        
                                        h4("Maximum Tree Depth"),
                                        helpText(
                                          "Control the maximum depth that the decision tree can reach.",
                                          "Note that, depending on what features are being used and the",
                                          "values of the other parameters, you may end up with a tree",
                                          "much shallower than the maximum."
                                        ),
                                        sliderInput(
                                          inputId = "max_depth",
                                          label = NULL,
                                          min = 2,
                                          max = 5,
                                          value = 5
                                        ),
                                        br(),
                                      ),
                                      mainPanel(
                                        fluidRow(
                                          label = NULL,
                                          br(),
                                          
                                          fluidRow(
                                            label = NULL,
                                            column(6,
                                                   h2("Importance of the variables based on number of mtry and depth tree."),
                                                   tagAppendAttributes(
                                                     textOutput("variable_importance"),
                                                     style = "white-space: pre-wrap; font-size: 17px;"
                                                   )),
                                            
                                            br(),br(),br(),
                                            
                                            plotOutput(outputId = "impt_bar_rforest"),
                                            br(),br(), br(),br(),br(), br(),br(),
                                            
                                            plotOutput(outputId = "impt_line_rforest")
                                            
                                          )
                                        )
                                      )
                                    )
                           )
)
)


### --- SERVER LOGIC FUNCTION --- ###

server = function(input, output, session) {
  
  ### --- Random forest --- ###
  # ### --- Regenerating the Random forest --- ###
  
  rforest = eventReactive(
    eventExpr = input$createModel_rforest,
    valueExpr = rftrain(
      features = c(allfeatures),
      ntree = as.integer(input$mtry)
    )
  )
  
  ### --- Training and test results for random forest --- ###
  
  training_results_rforest = eventReactive(
    eventExpr = input$createModel_rforest,
    valueExpr = testforest(rforest(), train_data)
  )
  test_results_rforest = eventReactive(
    eventExpr = input$testModel_rforest,
    valueExpr = testforest(rforest(), test_data)
  )
  
  ### --- Random forest visualisation --- ###
  
  output$training_scores_rforest = renderText(paste(calcScores(training_results_rforest()), collapse = "\n"))
  output$test_scores_rforest = renderText(paste(calcScores(test_results_rforest()), collapse = "\n"))
  output$impt_bar_rforest = renderPlot(plot(varImp(rforest()))) ### Visualising relevant importance level of input features
  output$impt_line_rforest = renderPlot(
    
    plot_multi_way_importance(
      measure_importance(rforest()$finalModel),
      x_measure = "gini_decrease",
      y_measure = "accuracy_decrease",
      size_measure = "p_value",
      no_of_labels = 5
    )
  )
  
  ### --- Decision Tree --- ###
  ### --- reconstruct the tree every time createModel is pressed --- ###
  
  tree = eventReactive(
    eventExpr = input$createModel,
    valueExpr = makeTree(
      features = c(input$allfeatures),
      min_split = input$min_split,
      min_bucket = input$min_bucket,
      max_depth = input$max_depth
    )
  )
  
  ### --- regenerate training results every time createModel is pressed --- ###
  
  training_results = eventReactive(
    eventExpr = input$createModel,
    valueExpr = useTree(tree(), train_data)
  )
  
  ### --- regenerate test results every time createModel is pressed --- ###
  test_results = eventReactive(
    eventExpr = input$testModel,
    valueExpr = useTree(tree(), test_data)
  )
  
  ### ---OUTPUT DISPLAY PREP --- ###
  ### --- assessment scores are each collapsed to display on a new line --- ###
  output$training_scores = renderText(
    paste(calcScores(training_results()), collapse = "\n")
  )
  output$test_scores = renderText(
    paste(calcScores(test_results()), collapse = "\n")
  )
  
  ### ---  frame for a plot of the decision tree --- ###
  output$tree_plot = renderPlot(
    
    ## --- prp takes an output from rpart and plots it (literally Plot RPart) Visualising decision tree --- ###
    prp(
      tree(), roundint = FALSE,
      
      # neaten up the nodes and edges, remove detailed labels
      
      extra = 0, branch = 0, varlen = 0,
      
      # colors spam terminals in red, non-spam terminals in blue
      
      box.col = c("cornflowerblue", "tomato", "grey", "brown", "green")[tree()$frame$yval]
      
    )
  )
}

shinyApp(ui = ui, server = server)













